workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    environment:
      android_signing:
        - titanius
      vars:
        PACKAGE_NAME: "app.titanius.launcher"
        BUILD_NAME: "0.1.$PROJECT_BUILD_NUMBER"
      groups:
        - github
      flutter: stable
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches      
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Run build_runner
        script: | 
          flutter packages pub run build_runner build - d
      - name: Flutter analyze
        script: | 
          flutter analyze
        ignore_failure: true
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: | 
          flutter build apk --release --build-name=$BUILD_NAME --build-number=$PROJECT_BUILD_NUMBER
      - name: Rename the apk file
        script: | 
          mv build/app/outputs/flutter-apk/app-release.apk \
            build/app/outputs/flutter-apk/titanius-launcher-$BUILD_NAME.apk
      - name: Upload APK to GitHub Releases
        script: |
          gh release create "$BUILD_NAME" --title "Release $BUILD_NAME" --notes "Automated release from CodeMagic" --draft "build/app/outputs/flutter-apk/titanius-launcher-$BUILD_NAME.apk"
    artifacts:
      - build/app/outputs/flutter-apk/titanius-launcher-$BUILD_NAME.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - launcher@titanius.app
        notify:
          success: false
          failure: true