workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - titanius
      vars:
        PACKAGE_NAME: "app.titanius.launcher"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Run build_runner
        script: | 
          flutter packages pub run build_runner build - d
      - name: Flutter analyze
        script: | 
          flutter analyze
        ignore_failure: true
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: | 
          flutter build apk --release --build-name=0.0.$PROJECT_BUILD_NUMBER --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - launcher@titanius.app
        notify:
          success: false
          failure: true